name: lux_run_ai
description: A Strava-inspired AI running buddy app
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^10.1.0
  flutter_tts: ^3.8.5
  vector_math: ^2.1.2

flutter:
  uses-material-design: true
